ods/routes/api_admin.py
import base64
from datetime import datetime

import flask
from flask.blueprints import Blueprint
import psutil

from .shared import server_data, package_json, packages_json
from ..exc import RemoteRegistrationFailed
from ..database.api import (
    all_registered_ods, new_registered_ods,
    update_registered_ods, new_uploaded_package,
    update_server_data
)
from ..api_clients.ods_client import ODSClient
from ..ods_files import move_staging_to_static
from ..tasks.notifications import send_new_package_command
from ..utilities import human_readable_bytes, human_readable_time, parse_url

blueprint = Blueprint('api_admin', __name__, url_prefix='/api/admin')


@blueprint.errorhandler(409)
def admin_error_conflict(error):
    flask.current_app.logger.error(error)
    flask.flash(
        'The action failed! There was a conflict with an existing resource.')
    return flask.jsonify(
        {'error': 'There was a conflict with an existing resource.'}), 409


@blueprint.route('/about', methods=['GET'])
def about():
    """Returns ODS application settings.

    .. :quickref: About; Returns ODS application settings.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/about HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "firewalled_mode": false,
            "iss": "e7becdda9a9046f6a78f69ef591e9835",
            "key": "r3Yt354eDTY0JkaiObpsM4krfkDzdZD9NNYwDr9aSk0=",
            "name": "Example ODS",
            "stage": "Prod",
            "url": "http://192.168.99.100"
        }

    """
    return server_data()


@blueprint.route('/about/update', methods=['POST'])
def about_update():
    """Updates ODS application information and settings.

    .. note::

        You cannot update the ``iss`` or ``key`` values!

    Accepted values for ``stage`` are: ``Dev``, ``Test``, ``Prod``

    Accepted values for ``firewalled_mode`` are: ``Enabled``, ``Disabled``

    .. :quickref: About; Updates ODS application settings.

    **Example Request:**

    .. sourcecode:: http

        POST /api/admin/about HTTP/1.1
        Content-Type: application/json

        {
            "name": "Example ODS",
            "url": "http://192.168.99.100",
            "firewalled_mode": "Disabled",
            "stage": "Prod"
        }

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 201 OK
        Content-Type: text/html

    """
    flask.current_app.logger.info('Updating server information...')
    data = flask.request.get_json()
    update_server_data(**data)
    return '', 201


@blueprint.route('/system', methods=['GET'])
def system():
    """Returns system information.

    ``disk_``, ``mem_``, and ``network_`` values are represented in total bytes.

    ``uptime`` is represented in total seconds.

    Human readable values are denoted by the ``_hr`` suffix.

    .. :quickref: System; Returns system information.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/system HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "cpu_count": 2,
            "disk_free": 60352081920,
            "disk_free_hr": "56.2 GB",
            "disk_total": 67371577344,
            "disk_total_hr": "62.7 GB",
            "disk_used": 3566796800,
            "disk_used_hr": "3.3 GB",
            "mem_available": 936255488,
            "mem_available_hr": "892.9 MB",
            "mem_total": 1567678464,
            "mem_total_hr": "1.5 GB",
            "mem_used": 444342272,
            "mem_used_hr": "423.8 MB",
            "network_bytes_received": 54346,
            "network_bytes_received_hr": "53.1 KB",
            "network_bytes_sent": 45694,
            "network_bytes_sent_hr": "44.6 KB",
            "uptime": 30806,
            "uptime_hr": "8:33:26"
        }

    """
    mem = psutil.virtual_memory()
    disk = psutil.disk_usage(flask.current_app.config['APP_DIR'])
    network = psutil.net_io_counters()
    uptime = int((datetime.utcnow() - datetime.utcfromtimestamp(
        psutil.boot_time())).total_seconds())

    data = {
        'cpu_count': int(psutil.cpu_count()),
        'mem_total': int(mem.total),
        'mem_total_hr': human_readable_bytes(int(mem.total)),
        'mem_used': int(mem.used),
        'mem_used_hr': human_readable_bytes(int(mem.used)),
        'mem_available': int(mem.available),
        'mem_available_hr': human_readable_bytes(int(mem.available)),
        'disk_total': int(disk.total),
        'disk_total_hr': human_readable_bytes(int(disk.total)),
        'disk_used': int(disk.used),
        'disk_used_hr': human_readable_bytes(int(disk.used)),
        'disk_free': int(disk.free),
        'disk_free_hr': human_readable_bytes(int(disk.free)),
        'network_bytes_sent': int(network.bytes_sent),
        'network_bytes_sent_hr': human_readable_bytes(int(network.bytes_sent)),
        'network_bytes_received': int(network.bytes_recv),
        'network_bytes_received_hr': human_readable_bytes(
            int(network.bytes_recv)),
        'uptime': uptime,
        'uptime_hr': human_readable_time(uptime)
    }

    return flask.jsonify(data), 200


@blueprint.route('/packages', methods=['GET'])
def list_packages():
    """Returns a list of all packages on the server. The ``package objects`` are
    nested under an ``items`` key.

    ``created`` value is in ISO 8601 format (without microseconds).

    ``created_ts`` value is a Unix timestamp (time since Epoch).

    ``file_size`` value is represented in total bytes.

    ``file_size_hr`` is a human readable representation.

    .. :quickref: Packages; Returns a list of all packages on the server.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/packages HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "items": [
                {
                    "created": "2017-11-11T03:15:54",
                    "created_ts": 1510370154,
                    "file_size": 3438044,
                    "file_size_hr": "3.3 MB",
                    "filename": "NoMAD.pkg",
                    "id": 1,
                    "sha1": "3fab53c6f12e3d4621b17f728e9b3c522bb90816",
                    "stage": "Prod",
                    "status": "Public",
                    "uuid": "28f7adde4f674873807a4c8c69b641d0"
                }
            ]
        }

    """
    return packages_json()


@blueprint.route('/packages/<package_id_or_name>', methods=['GET'])
def get_package(package_id_or_name):
    """Returns a single package by the database ID or filename.

    ``created`` value is in ISO 8601 format (without microseconds).

    ``created_ts`` value is a Unix timestamp (time since Epoch).

    ``file_size`` value is represented in total bytes.

    ``file_size_hr`` is a human readable representation.

    ``chunks`` is an array of indexed hashes for each 1 MB block of the file.

    .. :quickref: Packages; Returns a single package by the database ID or
        filename.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/packages/1 HTTP/1.1
        Accept: application/json

    .. sourcecode:: http

        GET /api/admin/packages/NoMAD.pkg HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "created": "2017-11-11T03:15:54",
            "created_ts": 1510370154,
            "file_size": 3438044,
            "file_size_hr": "3.3 MB",
            "filename": "NoMAD.pkg",
            "id": 1,
            "sha1": "3fab53c6f12e3d4621b17f728e9b3c522bb90816",
            "stage": "Prod",
            "status": "Public",
            "uuid": "28f7adde4f674873807a4c8c69b641d0"
            "chunks": [
                {
                    "index": 0,
                    "sha1": "f34fef9be0364d92424106c19596d3fcd1676635"
                },
                {
                    "index": 1,
                    "sha1": "93633f00f71d3b5494b23b74b37777bc07f9d713"
                },
                {
                    "index": 2,
                    "sha1": "9e0ca33c872fb9b5d7aa46fbd865c309db792c12"
                },
                {
                    "index": 3,
                    "sha1": "468521469da7fd40ee72f18e70bf578f055b3878"
                }
            ],
        }

    """
    return package_json(package_id_or_name)


@blueprint.route('/registered_ods', methods=['GET'])
def list_registered_ods():
    """Returns a list of all registered ODS instances. The ``ods server
    objects`` are nested under an ``items`` key.

    ``registered_on`` value is in ISO 8601 format (without microseconds).

    ``registered_on_ts`` value is a Unix timestamp (time since Epoch).

    .. :quickref: ODS; Returns a list of all registered ODS instances.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/registered_ods HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "items": [
                {
                    "firewalled_mode": false,
                    "id": 1,
                    "name": "Example ODS 2",
                    "registered_on": "2017-11-10T04:45:47",
                    "registered_on_ts": 1510289147,
                    "stage": "Prod",
                    "url": "http://192.168.99.101"
                }
            ]
        }

    """
    ods_json = {'items': [ods.serialize for ods in all_registered_ods()]}
    return flask.jsonify(ods_json), 200


@blueprint.route('/register', methods=['POST'])

ods/templates/modals/about_update.html
<div class="modal fade" id="aboutUpdate" tabindex="-1" role="dialog">
    <div class="modal-sm modal-dialog">
        <div class="modal-content">
            <form id="aboutUpdateForm">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="ods_name">Name</label>
                        <input type="text" class="form-control" id="ods_name" name="name" required/>
                    </div>

                    <div class="form-group">
                        <label for="ods_url">URL</label>
                        <input type="text" class="form-control" id="ods_url" name="url" required/>
                    </div>

                    <div class="form-group">
                        <label for="ods_stage">Deploy Stage</label>
                        <select class="form-control" name="stage" id="ods_stage" required>
                            <optgroup label="Deploy Stage">
                                <option>Prod</option>
                                <option>Test</option>
                                <option>Develop</option>
                            </optgroup>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="ods_firewalled">Firewalled Mode</label>
                        <select class="form-control" name="fw_mode" id="ods_firewalled" required>
                            <optgroup label="Firewalled Mode">
                                <option>Enabled</option>
                                <option>Disabled</option>
                            </optgroup>
                        </select>
                    </div>

                    <div class="modal-footer form-group">
                        <button class="btn" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-primary" type="submit" id="aboutUpdateSave">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var registerForm = $('#aboutUpdateForm');

        registerForm.on('submit', function (event) {
            //stop submit the form, we will post it manually.
            event.preventDefault();
            var jsonData = ConvertFormToJSON(registerForm);
            $("#aboutUpdateSave").prop("disabled", true);

            $.ajax({
                type: "POST",
                url: "{{ url_for('api_admin.about_update') }}",
                dataType: 'json',
                contentType: "application/json",
                data: JSON.stringify(jsonData),
                cache: false,
                success: function (data) {
                    console.log("SUCCESS: ", data);
                    location.reload();
                },
                error: function (e) {
                    console.log("ERROR: ", e);
                    console.log("ERROR MSG: ", e.responseText);
                    location.reload();
                }
            });
        });
    });
</script>