ods/routes/api_admin.py
import base64
from datetime import datetime

import flask
from flask.blueprints import Blueprint
import psutil

from .shared import server_data, package_json, packages_json
from ..exc import RemoteRegistrationFailed
from ..database.api import (
    all_registered_ods, new_registered_ods,
    update_registered_ods, new_uploaded_package,
    update_server_data
)
from ..api_clients.ods_client import ODSClient
from ..ods_files import move_staging_to_static
from ..tasks.notifications import send_new_package_command
from ..utilities import human_readable_bytes, human_readable_time, parse_url

blueprint = Blueprint('api_admin', __name__, url_prefix='/api/admin')


@blueprint.errorhandler(409)
def admin_error_conflict(error):
    flask.current_app.logger.error(error)
    flask.flash(
        'The action failed! There was a conflict with an existing resource.')
    return flask.jsonify(
        {'error': 'There was a conflict with an existing resource.'}), 409


@blueprint.route('/about', methods=['GET'])
def about():
    """Returns ODS application settings.

    .. :quickref: About; Returns ODS application settings.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/about HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "firewalled_mode": false,
            "iss": "e7becdda9a9046f6a78f69ef591e9835",
            "key": "r3Yt354eDTY0JkaiObpsM4krfkDzdZD9NNYwDr9aSk0=",
            "name": "Example ODS",
            "stage": "Prod",
            "url": "http://192.168.99.100"
        }

    """
    return server_data()


@blueprint.route('/about/update', methods=['POST'])
def about_update():
    """Updates ODS application information and settings.

    .. note::

        You cannot update the ``iss`` or ``key`` values!

    Accepted values for ``stage`` are: ``Dev``, ``Test``, ``Prod``

    Accepted values for ``firewalled_mode`` are: ``Enabled``, ``Disabled``

    .. :quickref: About; Updates ODS application settings.

    **Example Request:**

    .. sourcecode:: http

        POST /api/admin/about HTTP/1.1
        Content-Type: application/json

        {
            "name": "Example ODS",
            "url": "http://192.168.99.100",
            "firewalled_mode": "Disabled",
            "stage": "Prod"
        }

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 201 OK
        Content-Type: text/html

    """
    flask.current_app.logger.info('Updating server information...')
    data = flask.request.get_json()
    update_server_data(**data)
    return '', 201


@blueprint.route('/system', methods=['GET'])
def system():
    """Returns system information.

    ``disk_``, ``mem_``, and ``network_`` values are represented in total bytes.

    ``uptime`` is represented in total seconds.

    Human readable values are denoted by the ``_hr`` suffix.

    .. :quickref: System; Returns system information.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/system HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "cpu_count": 2,
            "disk_free": 60352081920,
            "disk_free_hr": "56.2 GB",
            "disk_total": 67371577344,
            "disk_total_hr": "62.7 GB",
            "disk_used": 3566796800,
            "disk_used_hr": "3.3 GB",
            "mem_available": 936255488,
            "mem_available_hr": "892.9 MB",
            "mem_total": 1567678464,
            "mem_total_hr": "1.5 GB",
            "mem_used": 444342272,
            "mem_used_hr": "423.8 MB",
            "network_bytes_received": 54346,
            "network_bytes_received_hr": "53.1 KB",
            "network_bytes_sent": 45694,
            "network_bytes_sent_hr": "44.6 KB",
            "uptime": 30806,
            "uptime_hr": "8:33:26"
        }

    """
    mem = psutil.virtual_memory()
    disk = psutil.disk_usage(flask.current_app.config['APP_DIR'])
    network = psutil.net_io_counters()
    uptime = int((datetime.utcnow() - datetime.utcfromtimestamp(
        psutil.boot_time())).total_seconds())

    data = {
        'cpu_count': int(psutil.cpu_count()),
        'mem_total': int(mem.total),
        'mem_total_hr': human_readable_bytes(int(mem.total)),
        'mem_used': int(mem.used),
        'mem_used_hr': human_readable_bytes(int(mem.used)),
        'mem_available': int(mem.available),
        'mem_available_hr': human_readable_bytes(int(mem.available)),
        'disk_total': int(disk.total),
        'disk_total_hr': human_readable_bytes(int(disk.total)),
        'disk_used': int(disk.used),
        'disk_used_hr': human_readable_bytes(int(disk.used)),
        'disk_free': int(disk.free),
        'disk_free_hr': human_readable_bytes(int(disk.free)),
        'network_bytes_sent': int(network.bytes_sent),
        'network_bytes_sent_hr': human_readable_bytes(int(network.bytes_sent)),
        'network_bytes_received': int(network.bytes_recv),
        'network_bytes_received_hr': human_readable_bytes(
            int(network.bytes_recv)),
        'uptime': uptime,
        'uptime_hr': human_readable_time(uptime)
    }

    return flask.jsonify(data), 200


@blueprint.route('/packages', methods=['GET'])
def list_packages():
    """Returns a list of all packages on the server. The ``package objects`` are
    nested under an ``items`` key.

    ``created`` value is in ISO 8601 format (without microseconds).

    ``created_ts`` value is a Unix timestamp (time since Epoch).

    ``file_size`` value is represented in total bytes.

    ``file_size_hr`` is a human readable representation.

    .. :quickref: Packages; Returns a list of all packages on the server.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/packages HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "items": [
                {
                    "created": "2017-11-11T03:15:54",
                    "created_ts": 1510370154,
                    "file_size": 3438044,
                    "file_size_hr": "3.3 MB",
                    "filename": "NoMAD.pkg",
                    "id": 1,
                    "sha1": "3fab53c6f12e3d4621b17f728e9b3c522bb90816",
                    "stage": "Prod",
                    "status": "Public",
                    "uuid": "28f7adde4f674873807a4c8c69b641d0"
                }
            ]
        }

    """
    return packages_json()


@blueprint.route('/packages/<package_id_or_name>', methods=['GET'])
def get_package(package_id_or_name):
    """Returns a single package by the database ID or filename.

    ``created`` value is in ISO 8601 format (without microseconds).

    ``created_ts`` value is a Unix timestamp (time since Epoch).

    ``file_size`` value is represented in total bytes.

    ``file_size_hr`` is a human readable representation.

    ``chunks`` is an array of indexed hashes for each 1 MB block of the file.

    .. :quickref: Packages; Returns a single package by the database ID or
        filename.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/packages/1 HTTP/1.1
        Accept: application/json

    .. sourcecode:: http

        GET /api/admin/packages/NoMAD.pkg HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "created": "2017-11-11T03:15:54",
            "created_ts": 1510370154,
            "file_size": 3438044,
            "file_size_hr": "3.3 MB",
            "filename": "NoMAD.pkg",
            "id": 1,
            "sha1": "3fab53c6f12e3d4621b17f728e9b3c522bb90816",
            "stage": "Prod",
            "status": "Public",
            "uuid": "28f7adde4f674873807a4c8c69b641d0"
            "chunks": [
                {
                    "index": 0,
                    "sha1": "f34fef9be0364d92424106c19596d3fcd1676635"
                },
                {
                    "index": 1,
                    "sha1": "93633f00f71d3b5494b23b74b37777bc07f9d713"
                },
                {
                    "index": 2,
                    "sha1": "9e0ca33c872fb9b5d7aa46fbd865c309db792c12"
                },
                {
                    "index": 3,
                    "sha1": "468521469da7fd40ee72f18e70bf578f055b3878"
                }
            ],
        }

    """
    return package_json(package_id_or_name)


@blueprint.route('/registered_ods', methods=['GET'])
def list_registered_ods():
    """Returns a list of all registered ODS instances. The ``ods server
    objects`` are nested under an ``items`` key.

    ``registered_on`` value is in ISO 8601 format (without microseconds).

    ``registered_on_ts`` value is a Unix timestamp (time since Epoch).

    .. :quickref: ODS; Returns a list of all registered ODS instances.

    **Example Request:**

    .. sourcecode:: http

        GET /api/admin/registered_ods HTTP/1.1
        Accept: application/json

    **Example Response:**

    .. sourcecode:: http

        HTTP/1.1 200 OK
        Content-Type: application/json

        {
            "items": [
                {
                    "firewalled_mode": false,
                    "id": 1,
                    "name": "Example ODS 2",
                    "registered_on": "2017-11-10T04:45:47",
                    "registered_on_ts": 1510289147,
                    "stage": "Prod",
                    "url": "http://192.168.99.101"
                }
            ]
        }

    """
    ods_json = {'items': [ods.serialize for ods in all_registered_ods()]}
    return flask.jsonify(ods_json), 200


@blueprint.route('/register', methods=['POST'])

ods/routes/web_admin.py
import flask
from flask.blueprints import Blueprint
from flask_login import (
    LoginManager, login_required, current_user, login_user, logout_user
)

from ..database.api import admin_login, admin_lookup

blueprint = Blueprint('web', __name__)
login_manager = LoginManager()


@blueprint.record_once
def web_on_load(state):
    login_manager.init_app(state.app)
    login_manager.login_view = ''


@blueprint.before_request
def web_before_request():
    flask.g.user = current_user


@blueprint.errorhandler(401)
def web_error_unauthorized(error):
    """401 error page"""
    flask.current_app.logger.error(error)
    flask.flash('You must log in to view this page')
    return flask.render_template('index.html'), 401


@login_manager.user_loader
def load_user(login_id):
    return admin_lookup(login_id)


@blueprint.route('/logout')
def logout():
    logout_user()
    return flask.redirect('')


@blueprint.route('/', strict_slashes=False, methods=['GET', 'POST'])
def index():
    if flask.request.method == 'GET':
        return flask.render_template('index.html')

    username = flask.request.form['username']
    password = flask.request.form['password']

    admin_user = admin_login(username, password)

    if admin_user is None:
        flask.flash('Username or Password is invalid')
        return flask.redirect('')

    login_user(admin_user)
    return flask.redirect(flask.request.args.get('next')
                          or flask.url_for('web.admin'))


@blueprint.route('/admin')
@login_required
def admin():
    return flask.render_template('admin.html'), 200


@blueprint.route('/packages')
@login_required
def packages():
    return flask.render_template('packages.html'), 200


@blueprint.route('/network')
@login_required
def network():
    return flask.render_template('network.html'), 200


@blueprint.route('/share/<filename>')
@blueprint.route('/Packages/<filename>')
def share_download(filename):
    return flask.send_from_directory(
        flask.current_app.config['SHARE_DIR'], filename, conditional=True), 200

ods/templates/admin.html
{% extends 'base.html' %}
{% block body_content %}

    {% include 'modals/about_update.html' %}

  <div class="container-fluid">

    <div class="col-sm-12 col-md-12 main">
        <script>
        $(document).ready(function() {
            document.getElementById("navbar-description").textContent=": Server Admin";
        })
        </script>
        
      <div class="table-responsive">
        <table class="table table-striped" id="about-ods">
          <thead>
            <tr>
              <th>Name</th>
              <th>URL</th>
              <th>ISS ID</th>
              <th>Key</th>
              <th>Stage</th>
              <th>Firewalled Mode</th>
              <th></th>
            </tr>
          </thead>
            <tbody>
                <tr>
                    <td id="ods-name"></td>
                    <td id="ods-url"></td>
                    <td id="ods-iss"></td>
                    <td>
                        <span id="ods-key" style="display:none;"></span>
                        <button id="ods-key-reveal" class="btn btn-jamf btn-xs">
                            Reveal <span class="glyphicon glyphicon-eye-open"></span>
                        </button>
                    <td id="ods-stage"></td>
                    <td id="ods-firewalled"></td>
                    <td>
                        <button class="btn btn-jamf btn-xs" data-toggle="modal"
                                data-target="#aboutUpdate" title="Edit">
                            <span class="glyphicon glyphicon-edit"></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
      </div>

      <h2 class="sub-header">System Information</h2>
      <div class="table-responsive">
        <table class="table table-striped" id="system-info">
          <thead>
            <tr>
              <th>CPU Count</th>
              <th>Total Memory</th>
              <th>Used Memory</th>
              <th>Available Memory</th>
              <th>Disk Space Total</th>
              <th>Disk Space Used</th>
              <th>Disk Space Free</th>
              <th>Network Bytes Sent</th>
              <th>Network Bytes Received</th>
              <th>System Uptime</th>
            </tr>
          </thead>
            <tbody>
                <tr>
                    <td id="sys-cpu"></td>
                    <td id="sys-mem-total"></td>
                    <td id="sys-mem-used"></td>
                    <td id="sys-mem-avail"></td>
                    <td id="sys-disk-total"></td>
                    <td id="sys-disk-used"></td>
                    <td id="sys-disk-free"></td>
                    <td id="sys-net-sent"></td>
                    <td id="sys-net-rcvd"></td>
                    <td id="sys-uptime"></td>
                </tr>
            </tbody>
        </table>
      </div>

        <h2 class="sub-header">API Tokens</h2>

    </div>
  </div>

    <script>
    $(document).ready(function(){
        $.ajax(
        {
            type: "GET",
            url: '{{ url_for('api_admin.about') }}',
            contentType: "application/json",
            dataType: "json",
            cache: false,
            success: function (jsonData) {
                var fw_mode = "";
                if (jsonData.firewalled_mode === true) {
                    fw_mode = 'Enabled'
                } else {
                    fw_mode = 'Disabled'
                }
                $('#ods-name').text(jsonData.name);
                $('#ods-url').text(jsonData.url);
                $('#ods-iss').text(jsonData.iss);
                $('#ods-key').text(jsonData.key);
                $('#ods-stage').text(jsonData.stage);
                $('#ods-firewalled').text(fw_mode);
            },

            error: function (msg) {
                alert(msg.responseText);
            }
        });
    })
    </script>

    <script>
    $(document).ready(function(){
        $("#ods-key-reveal").click(function(){
            $("#ods-key").show();
            $("#ods-key-reveal").hide();
        });
    });
    </script>

    <script>
    $(document).ready(function(){
        $.ajax(
        {
            type: "GET",
            url: '{{ url_for('api_admin.system') }}',
            contentType: "application/json",
            dataType: "json",
            cache: false,
            success: function (jsonData) {
                $('#sys-cpu').text(jsonData.cpu_count);
                $('#sys-mem-total').text(jsonData.mem_total_hr);
                $('#sys-mem-used').text(jsonData.mem_used_hr);
                $('#sys-mem-avail').text(jsonData.mem_available_hr);
                $('#sys-disk-total').text(jsonData.disk_total_hr);
                $('#sys-disk-used').text(jsonData.disk_used_hr);
                $('#sys-disk-free').text(jsonData.disk_free_hr);
                $('#sys-net-sent').text(jsonData.network_bytes_sent_hr);
                $('#sys-net-rcvd').text(jsonData.network_bytes_received_hr);
                $('#sys-uptime').text(jsonData.uptime_hr);
            },

            error: function (msg) {
                alert(msg.responseText);
            }
        });
    })
    </script>

{% endblock %}

ods/templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="ODS web admin console">
    <meta name="author" content="Bryson Tyrrell">
    <link rel="icon" href="../static/img/favicon.ico">

    <title>ODS Web Admin</title>

    <!-- Bootstrap core JavaScript -->
    <script src="../static/js/jquery.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
    <script src="../static/js/bootstrap-filestyle.min.js"></script>

    <script src="../static/js/custom.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../static/css/custom.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  {% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissable fade in" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}
  {% endwith %}

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="/">ODS <span id="navbar-description"></span></a>
        </div>
      
        <div id="navbar" class="navbar-collapse collapse">

        {% if g.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('web.admin') }}">Admin</a></li>
            <li><a href="{{ url_for('web.packages') }}">Packages</a></li>
            <li><a href="{{ url_for('web.network') }}">Network</a></li>
            <li><a href="{{ url_for('web.logout') }}">Logout <span class="glyphicon glyphicon-log-out"></span></a></li>
          </ul>
        {% else %}
          <form class="navbar-form navbar-right" method="post" action="/">
            <div class="form-group">
              <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" name="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-jamf">
              Login <span class="glyphicon glyphicon-log-in"></span>
            </button>
          </form>
        {% endif %}

        <script>
            $(document).ready(function() {
                $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
            });
        </script>

        </div>
      </div>
    </nav>

    {% block body_content %}
    {% endblock %}

    <footer style="padding: 10px"></footer>
  </body>

</html>

ods/templates/index.html
{% extends 'base.html' %}
{% block body_content %}

    <div class="container-fluid">

        <div class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 main">
          <h1 class="page-header">Welcome to the ODS</h1>
        </div>

    </div>

{% endblock %}

ods/templates/network.html
{% extends 'base.html' %}
{% block body_content %}
  <div class="container-fluid">

    <div class="col-sm-12 col-md-12 main">
        <script>
        $(document).ready(function() {
            document.getElementById("navbar-description").textContent=": Network";
        })
        </script>

        <h2 class="sub-header">Register with a ODS</h2>
        <div class="container-fluid">
              <form class="form-inline" id="registerODS" method="post">
                  <div class="row">
                      <div class="form-group">
                          <div class="input-group">
                              <span class="input-group-addon">URL</span>
                              <input type="text" class="form-control" id="ods_url" name="url" required/>
                          </div>
                      </div>

                      <div class="form-group">
                          <div class="input-group">
                              <span class="input-group-addon">ISS ID</span>
                              <input type="text" class="form-control" id="ods_iss" name="iss_id" required/>
                          </div>
                      </div>

                      <div class="form-group">
                          <div class="input-group">
                              <span class="input-group-addon">Key</span>
                              <input type="password" class="form-control" id="ods_key" name="key" required/>
                          </div>
                      </div>

                      <div class="form-group">
                          <input class="btn btn-jamf" type="submit" value="Register" id="odsBtnSubmit"/>
                      </div>
                  </div>
              </form>
          </div>

        <h2 class="sub-header">Registered ODSs</h2>
        <div class="table-responsive">
            <table class="table table-striped" id="registered-ods-list">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>URL</th>
                        <th>Date Registered</th>
                        <th>Stage</th>
                        <th>Firewalled Mode</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody/>
            </table>
        </div>

    </div>
  </div>

    <script>
    $(document).ready(function () {
        var registerForm = $('#registerODS');

        registerForm.on('submit', function (event) {
            //stop submit the form, we will post it manually.
            event.preventDefault();

            var jsonData = ConvertFormToJSON(registerForm);

            $("#odsBtnSubmit").prop("disabled", true);

            $.ajax({
                type: "POST",
                url: "{{ url_for('api_admin.register_ods') }}",
                dataType: 'json',
                contentType: "application/json",
                data: JSON.stringify(jsonData),
                cache: false,
                success: function (data) {
                    console.log("SUCCESS: ", data);
                    location.reload();
                },
                error: function (e) {
                    console.log("ERROR: ", e);
                    console.log("ERROR MSG: ", e.responseText);
                    location.reload();
                }
            });
        });
    });
    </script>

    <script>
    $(document).ready(function(){
        $.ajax(
        {
            type: "GET",
            url: '{{ url_for('api_admin.list_registered_ods') }}',
            contentType: "application/json",
            dataType: "json",
            cache: false,
            success: function (jsonData) {
                var fw_mode = "";
                if (jsonData.firewalled_mode === true) {
                    fw_mode = 'Enabled'
                } else {
                    fw_mode = 'Disabled'
                }
                var table_body = '';
                $.each(jsonData.items, function(i, item) {
                    table_body += '<tr>' +
                    '<td>' + item.name + '</td>' +
                    '<td>' + item.url + '</td>' +
                    '<td>' + ConvertTimestamp(item.registered_on_ts) + '</td>' +
                    '<td>' + item.stage + '</td>' +
                    '<td>' + fw_mode + '</td>' +
                    '<td></td></tr>';
                });
                $('#registered-ods-list tbody').html(table_body);
            },

            error: function (msg) {
                alert(msg.responseText);
            }
        });
    })
    </script>

{% endblock %}

ods/templates/packages.html
{% extends 'base.html' %}
{% block body_content %}
  <div class="container-fluid">
      <div class="col-sm-12 col-md-12 main">

          <script>
          $(document).ready(function() {
              document.getElementById("navbar-description").textContent=": Package Manager";
          })
          </script>

          <h2 class="sub-header">Upload a Package</h2>
          <div class="container-fluid">
              <form class="form-inline" id="packageUpload" method="post" enctype="multipart/form-data">
                  <div class="row">
                      <div class="form-group">
                          <input type="file" class="filestyle" data-icon="false" data-buttonText="Select File" data-buttonBefore="true" data-placeholder="No file selected..." name="file" required/>
                      </div>

                      <div class="form-group">
                          <select class="form-control" name="stage" id="stage-select" required>
                              <optgroup label="Deploy Stage">
                                  <option>Prod</option>
                                  <option>Test</option>
                                  <option>Develop</option>
                              </optgroup>
                          </select>
                      </div>

                      <div class="form-group">
                          <input class="btn btn-jamf" type="submit" value="Upload" id="pkgBtnSubmit"/>
                      </div>
                  </div>
              </form>
          </div>

          <h2 class="sub-header">Available Packages</h2>
          <div class="table-responsive">
            <table class="table table-striped" id="package-list">
              <thead>
                <tr>
                  <th>Filename</th>
                  <th>Size</th>
                  <th>SHA1 Hash</th>
                  <th>State</th>
                  <th>Stage</th>
                </tr>
              </thead>
              <tbody/>
            </table>
          </div>

    </div>
  </div>

    <script>
    $(document).ready(function(){
        $.ajax(
        {
            type: "GET",
            url: '{{ url_for('api_admin.list_packages') }}',
            contentType: "application/json",
            dataType: "json",
            cache: false,
            success: function (data) {
                var table_body = '';
                $.each(data.items, function(i, item) {
                    table_body += '<tr>' +
                    '<td>' + item.filename + '</td>' +
                    '<td>' + item.file_size_hr + '</td>' +
                    '<td>' + item.sha1 + '</td>' +
                    '<td>' + item.status + '</td>' +
                    '<td>' + item.stage + '</td></tr>';
                });
                $('#package-list tbody').html(table_body);
            },

            error: function (msg) {
                alert(msg.responseText);
            }
        });
    })
    </script>

    <script>
    $(document).ready(function () {
        $("#pkgBtnSubmit").click(function (event) {
            //stop submit the form, we will post it manually.
            event.preventDefault();
            var form = new FormData($('#packageUpload')[0]);
            $("#pkgBtnSubmit").prop("disabled", true);
            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                url: "{{ url_for('api_admin.upload_file') }}",
                data: form,
                processData: false,
                contentType: false,
                cache: false,
                success: function (data) {
                    console.log("SUCCESS : ", data);
                    location.reload();
                },
                error: function (e) {
                    console.log("ERROR : ", e);
                    console.log("ERROR MSG: ", e.responseText);
                    location.reload();
                }
            });
        });
    });
    </script>

{% endblock %}